version: '3'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
     - 'pgdata:/var/lib/postgresql/data'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    image: sami0727/docker_rel:latest
    environment:
      DATABASE_URL: ecto://postgres:postgres@10.0.9.100/docker_rel_dev
      SECRET_KEY_BASE: HGF1ekWu4VWXZDLby40lUOJFN2dufDptrfr3C1NwwvZFeWmFYxSvUIFTc9/A/Gt/
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: docker_rel_dev
      PGPORT: 5432
      PGHOST: 10.0.9.100
    ports:
      - 4040:4040
    depends_on:
      - db
  
volumes:
  pgdata:
