version: '3.7'

services:

  postgres:
    image: postgres:16
    container_name: vscode_remote_postgres
    restart: always
    ports:
     - 15432:5432
    volumes:
     - ./docker/data/postgres:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vscode_remote_app
    ports:
      - 4050:4050
    volumes:
      - .:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    command: sleep infinity
    depends_on:
      - postgres
  
# volumes:
#   pgdata:
