import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
# config :docker_rel, DockerRelWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"
config :docker_rel, DockerRelWeb.Endpoint, server: true,
check_origin: [
  "http://localhost:4050",
  "http://127.0.0.1:4050"
],
http: [port: 4050],
url: [host: "localhost", port: 4050],
cache_static_manifest: "priv/static/cache_manifest.json"
# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: DockerRel.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
